version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/code

volumes:
  postgres_data: