FROM python:3.8-slim
WORKDIR /code
COPY requirements.txt /code/
COPY . /code/

RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]