name: Build and Deploy to Cloud Run

# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]

on:
  push:
    paths:
      - 'api/**'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Push Docker image
      run: |
        cd api
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-data-repo:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-data-repo:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-data-repo-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-data-repo:$GITHUB_SHA --region us-central1 --platform managed --allow-unauthenticated
